# Created with komac v2.14.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Fluxzy.Fluxzy
PackageVersion: 1.39.50.33872
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: fluxzy.exe
  PortableCommandAlias: fluxzy
- RelativeFilePath: fluxzynetcap.exe
  PortableCommandAlias: fluxzynetcap
ReleaseDate: 2026-10-10
ArchiveBinariesDependOnPath: true
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/haga-rak/fluxzy.core/releases/download/v1.39.50.33872/fluxzy-cli-1.39.50.33872-win-x86.zip
  InstallerSha256: AE1D02D9640C5BEBC8DA928BCB2855BEC4650B962594CAF1F9084FFA1F5F4487
- Architecture: x86
  InstallerUrl: https://github.com/haga-rak/fluxzy.core/releases/download/v1.39.50.33872/fluxzy-cli-1.39.50.33872-win-x86.zip
  InstallerSha256: AE1D02D9640C5BEBC8DA928BCB2855BEC4650B962594CAF1F9084FFA1F5F4487
  AppsAndFeaturesEntries:
  - DisplayName: Fluxzy (ARM64)
- Architecture: x86
  InstallerUrl: https://github.com/haga-rak/fluxzy.core/releases/download/v1.39.50.33872/fluxzy-cli-1.39.50.33872-win-x86.zip
  InstallerSha256: AE1D02D9640C5BEBC8DA928BCB2855BEC4650B962594CAF1F9084FFA1F5F4487
  AppsAndFeaturesEntries:
  - DisplayName: Fluxzy (x64)
ManifestType: installer
ManifestVersion: 1.10.0
